#ifndef KEYVALUESTORAGE_GLOBAL_H
#define KEYVALUESTORAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KEYVALUESTORAGE_LIBRARY)
#  define KEYVALUESTORAGE_EXPORT Q_DECL_EXPORT
#else
#  define KEYVALUESTORAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // KEYVALUESTORAGE_GLOBAL_H
