name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: sudo apt-get update && sudo apt-get install -y qt5-qmake qtbase5-dev qtdeclarative5-dev
      
    - name: Build project
      run: qmake -r Key-Value_Storage.pro

    - name: Run tests
      run: ctest --output-on-failure
