name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential qt5-default qtbase5-dev qtdeclarative5-dev
    
    - name: Build project
      run: |
        cd ../Key-Value_Storage.pro
        qmake -config release
        make
        
    - name: Build Test project
      run: |
          cd ../KeyStorageTest/KeyStorageTest.pro
          qmake -config release
          make

    - name: Run tests
      run: |
        cd ../KeyStorageTest
        ./KeyStorageTest -test
      
