name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt Creator
      uses: jurplel/install-qt-action@v2
      with:
        version: 'latest'

    - name: Configure project
      run: qmake -r

    - name: Build project
      run: make

    - name: Run tests
      run: ctest --output-on-failure
